export enum Strings {
  ResourceName = 'Big City Life Code Editor',
  ScriptURL = 'https://github.com/bcl-team/bcl-runcode',
  Explorer = 'EXPLORER',
  JavaScript = 'JavaScript',
  Lua = 'Lua',
  Client = 'Client',
  Server = 'Server',
  CreateScript = 'Create Script',
  ScriptName = 'Script Name',
  NewScript = 'New Script',
  Output = 'Output',
  ExecuteCode = 'Execute Code',
  ClearOutput = 'Clear Output',
}
